/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creators */
        get: operations["list_creators_api_creators_get"];
        put?: never;
        /**
         * Add Creator
         * @description 收录博主 = 起一个 `add_creator` 任务（要跟 302、要拉资料，不是纯本地写）。
         */
        post: operations["add_creator_api_creators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creators/{creator_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Creator */
        get: operations["get_creator_api_creators__creator_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creators/{creator_id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Tracking
         * @description 改跟踪开关。**只认 `set_tracking` 一个入口**（V1 §7.24：值必须是真 bool）。
         *
         *     `TrackingRequest.tracking` 是 pydantic `bool` —— JSON 里的 `"true"` 字符串会被
         *     pydantic 拒成 422，绝不会被塞进 `set_tracking` 落成 0。这一层是 §7.24 的第一道闸。
         */
        patch: operations["set_tracking_api_creators__creator_id__tracking_patch"];
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global Events */
        get: operations["global_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 进程活着 + 版本号。前端侧边栏的连接指示灯用。
         *
         *     **不打数据库**：`/health` 是"进程在不在"，不是"依赖好不好的" —— 后者是 `/preflight`。
         *     把 DB 探活塞这里会让一次 SQLite 卡顿看起来像服务挂了。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Manifests */
        get: operations["list_manifests_api_manifests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifests/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_api_manifests__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platforms */
        get: operations["list_platforms_api_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/{platform}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Platform Config
         * @description 平台配置（权威源来自 ConfigManager）+ 运行态健康镜像。
         *
         *     健康取不到就是 `None`（从没检查过），不编一个 ok —— `PlatformRecord.is_healthy`
         *     只认显式 `"ok"`（V1 §7.20 的同一口径）。
         */
        get: operations["get_platform_config_api_platforms__platform__config_get"];
        /**
         * Update Platform Config
         * @description 校验 → 原子写盘 → 热重载 → 广播 `CONFIG_CHANGED` → 让适配器实例作废。
         */
        put: operations["update_platform_config_api_platforms__platform__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/{platform}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform Schema
         * @description 配置类的 JSON Schema，前端据此自动渲染表单（`ui:advanced` 折叠高级字段）。
         */
        get: operations["platform_schema_api_platforms__platform__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preflight
         * @description 同步跑一遍预检并返回红绿灯。**不建 task_run、不写清单**（这是一次只读探针）。
         *
         *     与"跑一个 preflight 任务"的区别：那个会留下一条运行历史，而 Settings 页只想问一句
         *     "现在环境怎么样"刷新显示。用一个临时 task_id 的 `TaskContext` 直接调 handler。
         */
        get: operations["preflight_api_preflight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description 当前可运行的任务（平台开关 + `implemented` 过滤后）。
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_tasks_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_tasks_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description 协作式取消：置位 `CancelToken`。返回 False 表示这条已经不在跑了（诚实回执，不转圈）。
         */
        post: operations["cancel_run_api_tasks_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_tasks_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Task
         * @description 启动任务，立即返回 task_id（202）。
         *
         *     参数校验失败 / 平台禁用 / 未实现 → `scheduler.submit` 抛 `ValidationError` / `TaskRejected`，
         *     交全局异常处理器翻成 422（不在这里 catch —— 那样每个入口都要抄一遍映射）。
         */
        post: operations["run_task_api_tasks__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Schema */
        get: operations["task_schema_api_tasks__name__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_api_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/single-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collect Single Link */
        post: operations["collect_single_link_api_videos_single_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_api_videos__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Hide Video
         * @description 隐藏（情报流的"删除"）。不删媒体、不删稿子 —— 文件是全库唯一的原始产物。
         */
        patch: operations["hide_video_api_videos__video_id__hide_patch"];
        trace?: never;
    };
    "/api/videos/{video_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_videos__video_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Unhide Video */
        patch: operations["unhide_video_api_videos__video_id__unhide_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCreatorRequest */
        AddCreatorRequest: {
            /** Platform */
            platform?: string | null;
            /**
             * Tracking
             * @default true
             */
            tracking: boolean;
            /** Url */
            url: string;
        };
        /** CancelResponse */
        CancelResponse: {
            /** Cancelled */
            cancelled: boolean;
            /** Task Id */
            task_id: string;
        };
        /** ConfigUpdateResponse */
        ConfigUpdateResponse: {
            /** Changed Fields */
            changed_fields?: string[];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Platform */
            platform: string;
            /**
             * Requires Restart
             * @default false
             */
            requires_restart: boolean;
        };
        /**
         * Creator
         * @description DB 行（creators 表的 Pydantic 映射）。
         *
         *     V1 §7.24 看护：is_tracking 必须真布尔，DB 层有 CHECK (is_tracking IN (0, 1))。
         */
        Creator: {
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Follower Count */
            follower_count?: number | null;
            /** Id */
            id: number;
            /** Is Tracking */
            is_tracking: boolean;
            /** Metadata Json */
            metadata_json: string;
            /** Name */
            name: string;
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
            /** Profile Url */
            profile_url: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Version */
            version: string;
        };
        /** HideRequest */
        HideRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * ManifestRecord
         * @description DB 行（manifests 表的 Pydantic 映射）。
         *
         *     清单**双写**：文件（`data/manifests/<...>.json`，审计与离线分析）
         *     + SQLite（前端历史列表查询）。V1 只有文件，于是"最近 20 次任务"
         *     要 glob 目录 + 逐个读 JSON + 排序 —— 慢，而且文件名格式一变就全废。
         *
         *     `content_json` 是完整清单的冗余副本：详情/审计仍然读文件（那才是权威源），
         *     这里存一份只是为了列表页不用回磁盘。
         */
        ManifestRecord: {
            /** Content Json */
            content_json: string;
            /** File Path */
            file_path: string;
            /** Id */
            id: number;
            /**
             * Schema Version
             * @default 2.0
             */
            schema_version: string;
            /** Task Id */
            task_id: string;
            /**
             * Written At
             * Format: date-time
             */
            written_at: string;
        };
        /** ManifestSummary */
        ManifestSummary: {
            /** File Path */
            file_path: string;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Summary */
            summary: {
                [key: string]: number | string;
            };
            /** Task Id */
            task_id: string;
            /** Written At */
            written_at: unknown;
        };
        /** PagedResult[Video] */
        PagedResult_Video_: {
            /** Items */
            items: components["schemas"]["Video"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** PlatformSummary */
        PlatformSummary: {
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Implemented */
            implemented: boolean;
            /** Name */
            name: string;
        };
        /** PlatformsResponse */
        PlatformsResponse: {
            /** Platforms */
            platforms: components["schemas"]["PlatformSummary"][];
        };
        /** RunDetail */
        RunDetail: {
            /** Manifest */
            manifest?: {
                [key: string]: unknown;
            } | null;
            run: components["schemas"]["TaskRunRecord"];
        };
        /**
         * SingleLinkParams
         * @description 收一条作品（`single_link`）：解析链接 → 判平台 → 走对应适配器。
         */
        SingleLinkParams: {
            /**
             * Url
             * @description 作品链接（分享短链也可以）
             */
            url: string;
        };
        /** TaskAccepted */
        TaskAccepted: {
            /** Task Id */
            task_id: string;
        };
        /** TaskInfo */
        TaskInfo: {
            /** Cancellable */
            cancellable: boolean;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** Platforms */
            platforms: string[];
            /** Timeout Seconds */
            timeout_seconds: number | null;
        };
        /**
         * TaskRunRecord
         * @description DB 行（task_runs 表的 Pydantic 映射）。
         *
         *     与 `TaskResult` 的区别：`TaskResult` 是**一次执行的产出**（handler 返回它），
         *     `TaskRunRecord` 是**这次执行的档案**（含 id / 时间戳 / 进度 / 清单路径）。
         *     前者活在一次调用里，后者要能被"任务历史"页面翻出来。
         *
         *     V1 §2 契约二看护：`status` 为终态时 `ended_at` 必填，DB 层有 CHECK 约束
         *     `status = 'running' OR ended_at IS NOT NULL`。
         */
        TaskRunRecord: {
            /**
             * Config Snapshot Json
             * @default {}
             */
            config_snapshot_json: string;
            /** Ended At */
            ended_at?: string | null;
            /** Error Text */
            error_text?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Manifest Path */
            manifest_path?: string | null;
            /**
             * Params Json
             * @default {}
             */
            params_json: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "success" | "partial" | "failed" | "timeout" | "cancelled";
            /** Summary Json */
            summary_json?: string | null;
            /** Task Name */
            task_name: string;
        };
        /** TrackingRequest */
        TrackingRequest: {
            /** Tracking */
            tracking: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Video
         * @description DB 行（videos 表的 Pydantic 映射）。
         *
         *     V1 §7.25 看护：is_hidden + hidden_at + hidden_reason 内化墓碑。
         */
        Video: {
            /** Comment Count */
            comment_count?: number | null;
            /** Cover Path */
            cover_path?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Creator Id */
            creator_id?: number | null;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Hidden At */
            hidden_at?: string | null;
            /** Hidden Reason */
            hidden_reason?: string | null;
            /** Id */
            id: number;
            /**
             * Is Hidden
             * @default false
             */
            is_hidden: boolean;
            /** Like Count */
            like_count?: number | null;
            /**
             * Media Aux Paths Json
             * @default []
             */
            media_aux_paths_json: string;
            /** Media Path */
            media_path?: string | null;
            /** Media Source */
            media_source?: string | null;
            /**
             * Metadata Json
             * @default {}
             */
            metadata_json: string;
            /** Platform */
            platform: string;
            /** Platform Video Id */
            platform_video_id: string;
            /** Published At */
            published_at?: string | null;
            /** Share Count */
            share_count?: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** View Count */
            view_count?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_creators_api_creators_get: {
        parameters: {
            query?: {
                platform?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_creator_api_creators_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCreatorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_creator_api_creators__creator_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creator_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tracking_api_creators__creator_id__tracking_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creator_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_events_api_events_get: {
        parameters: {
            query?: {
                /** @description 逗号分隔的 EventType */
                types?: string | null;
                since?: string | null;
                /** @description 只看这一次任务（带上才回放历史） */
                task_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_manifests_api_manifests_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_api_manifests__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platforms_api_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformsResponse"];
                };
            };
        };
    };
    get_platform_config_api_platforms__platform__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_platform_config_api_platforms__platform__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_schema_api_platforms__platform__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_api_preflight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInfo"][];
                };
            };
        };
    };
    list_runs_api_tasks_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_tasks_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_tasks_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_tasks_runs__run_id__events_get: {
        parameters: {
            query?: {
                types?: string | null;
                since?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_task_api_tasks__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_schema_api_tasks__name__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_videos_api_videos_get: {
        parameters: {
            query?: {
                platform?: string | null;
                creator_id?: number | null;
                since?: string | null;
                search?: string | null;
                hidden?: "visible" | "hidden" | "all";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult_Video_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collect_single_link_api_videos_single_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SingleLinkParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_video_api_videos__video_id__hide_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_videos__video_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unhide_video_api_videos__video_id__unhide_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
