/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/benchmark-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Benchmark Analysis
         * @description 拆解一条作品。纯本地计算：不联网、不调模型、不写库。
         */
        get: operations["benchmark_analysis_api_benchmark_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creators */
        get: operations["list_creators_api_creators_get"];
        put?: never;
        /**
         * Add Creator
         * @description 收录博主 = 起一个 `add_creator` 任务（要跟 302、要拉资料，不是纯本地写）。
         */
        post: operations["add_creator_api_creators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creators/{creator_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Creator */
        get: operations["get_creator_api_creators__creator_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creators/{creator_id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Tracking
         * @description 改跟踪开关。**只认 `set_tracking` 一个入口**（V1 §7.24：值必须是真 bool）。
         *
         *     `TrackingRequest.tracking` 是 pydantic `bool` —— JSON 里的 `"true"` 字符串会被
         *     pydantic 拒成 422，绝不会被塞进 `set_tracking` 落成 0。这一层是 §7.24 的第一道闸。
         */
        patch: operations["set_tracking_api_creators__creator_id__tracking_patch"];
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drafts
         * @description 列表。`?status=` 不传就是全部；传了非法值由 FastAPI 的 `Literal` 校验挡成 422，
         *     不是一条悄悄返回空列表的查询。
         */
        get: operations["list_drafts_api_drafts_get"];
        put?: never;
        /** Create Draft */
        post: operations["create_draft_api_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_drafts__draft_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Draft
         * @description 真删草稿。这是**唯一**会销毁人写出来的文字的路径，所以只挂在显式 DELETE 上。
         */
        delete: operations["delete_draft_api_drafts__draft_id__delete"];
        options?: never;
        head?: never;
        /** Update Draft */
        patch: operations["update_draft_api_drafts__draft_id__patch"];
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global Events */
        get: operations["global_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Table
         * @description 导出一张表。`hidden` 的默认值与 `/api/videos` 一致（visible）——
         *     导出默认含隐藏行会让人以为"删掉的作品还在"，那是另一种口径分叉。
         */
        get: operations["export_table_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-draft-script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Draft Script
         * @description 按模板拼一份脚本。**纯本地拼装**：不联网、不调模型、不写库、不写文件。
         */
        post: operations["create_draft_script_api_generate_draft_script_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 进程活着 + 版本号。前端侧边栏的连接指示灯用。
         *
         *     **不打数据库**：`/health` 是"进程在不在"，不是"依赖好不好的" —— 后者是 `/preflight`。
         *     把 DB 探活塞这里会让一次 SQLite 卡顿看起来像服务挂了。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Manifests */
        get: operations["list_manifests_api_manifests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifests/{manifest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_api_manifests__manifest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform-control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Platform Control
         * @description 四家共用的那一个总闸。
         */
        get: operations["get_platform_control_api_platform_control_get"];
        /**
         * Update Platform Control
         * @description 写 `app.yaml` 的 `platform_control` 段 → 当场生效 → 重排采集 job → 发事件。
         *
         *     与两条平台配置 PUT 同一条纪律：**运行时不听文件变化**，所以"生效"必须显式做。
         *     这里比它们少一步：没有需要推的快照 —— 注册表拿的是总闸的**闭包**、
         *     调度器与 runner 握着的是同一个 `AppConfig` 实例，而 `write_platform_control`
         *     原地换的就是那个实例上的字段（换指针会让没跟着换的持有者继续用旧值，
         *     症状是"设置页说总闸已开，任务列表还是空的"）。
         *
         *     重排采集 job 必须在写盘**之后**：`reschedule_collect_jobs` 读的就是那份配置。
         */
        put: operations["update_platform_control_api_platform_control_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platforms */
        get: operations["list_platforms_api_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/{platform}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Platform Config
         * @description 平台配置（权威源来自 ConfigManager）+ 运行态健康镜像。
         *
         *     健康取不到就是 `None`（从没检查过），不编一个 ok —— `PlatformRecord.is_healthy`
         *     只认显式 `"ok"`（V1 §7.20 的同一口径）。
         */
        get: operations["get_platform_config_api_platforms__platform__config_get"];
        /**
         * Update Platform Config
         * @description 校验 → 原子写盘 → 热重载 → 广播 `CONFIG_CHANGED` → 让适配器实例作废。
         */
        put: operations["update_platform_config_api_platforms__platform__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/{platform}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform Schema
         * @description 配置类的 JSON Schema，前端据此自动渲染表单（`ui:advanced` 折叠高级字段）。
         */
        get: operations["platform_schema_api_platforms__platform__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preflight
         * @description 同步跑一遍预检并返回红绿灯。**不建 task_run、不写清单**（这是一次只读探针）。
         *
         *     与"跑一个 preflight 任务"的区别：那个会留下一条运行历史，而 Settings 页只想问一句
         *     "现在环境怎么样"刷新显示。用一个临时 task_id 的 `TaskContext` 直接调 handler。
         */
        get: operations["preflight_api_preflight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schedule
         * @description 定时采集的当前配置，与已经排上的 job。
         */
        get: operations["get_schedule_api_schedule_get"];
        /**
         * Update Schedule
         * @description 写 `app.yaml` 的 scheduler 段 → 热更内存 → 当场重排采集 job → 发 `CONFIG_CHANGED`。
         *
         *     与平台配置那条 PUT 同一条纪律：**运行时不听文件变化**，改了不生效是设计而不是 bug。
         *     所以"生效"这一步必须显式做，不许留给下一次启动。
         */
        put: operations["update_schedule_api_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Now
         * @description 立刻排队一次该平台的采集，参数用定时任务那一套（`collect_limit`）。
         *
         *     202 说的只是"已排队"，不是"已采到"。参数校验失败 / 平台被关掉 → `submit` 抛
         *     `ValidationError` / `TaskRejected`，交全局异常处理器翻成 422 —— 不在这里 catch，
         *     否则每个入口都要抄一遍映射（V1 §7.10 那一族）。
         */
        post: operations["run_now_api_schedule_run_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description 当前可运行的任务（平台开关 + 总闸 + `implemented` 过滤后）。
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_tasks_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_tasks_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description 协作式取消：置位 `CancelToken`。返回 False 表示这条已经不在跑了（诚实回执，不转圈）。
         */
        post: operations["cancel_run_api_tasks_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_tasks_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Task
         * @description 启动任务，立即返回 task_id（202）。
         *
         *     参数校验失败 / 平台禁用 / 未实现 → `scheduler.submit` 抛 `ValidationError` / `TaskRejected`，
         *     交全局异常处理器翻成 422（不在这里 catch —— 那样每个入口都要抄一遍映射）。
         */
        post: operations["run_task_api_tasks__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{name}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Schema */
        get: operations["task_schema_api_tasks__name__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_topics_get"];
        put?: never;
        /**
         * Create Topic
         * @description 建一条选题。
         *
         *     空白的 `name` 在 `TopicDraft` 里被拒（那里才是规则的唯一出处：库里那一半是
         *     UNIQUE 而不是 CHECK，空串合法，所以规则必须有人守）。这里只是把那句人话
         *     翻成 422，**不在 `TopicCreate` 上再抄一遍校验规则** —— 两处清单迟早漂开。
         */
        post: operations["create_topic_api_topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_api_topics__topic_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Topic
         * @description 真删。今天没有任何表引用 `topics.id`（`video_topics` 未落地，ADR-0021），
         *     所以删掉就是一行少一行 —— 那条前提变了要回来看 `TopicRepository.delete()`。
         */
        delete: operations["delete_topic_api_topics__topic_id__delete"];
        options?: never;
        head?: never;
        /** Update Topic */
        patch: operations["update_topic_api_topics__topic_id__patch"];
        trace?: never;
    };
    "/api/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Videos
         * @description 分页列作品。`sort=benchmark` 是"按点赞数从大到小"（T6.6 的爆款回溯入口用）。
         *
         *     为什么是一个 `sort` 值而不是 `min_likes` 阈值参数：入口要回答的是"这个人历史上
         *     水花最大的几条"，而"多少算爆款"各家平台差一个数量级（抖音十万赞是日常，
         *     B 站一千算爆款）—— 阈值放进筛选器会伪装成一个平台无关的常量。排序 + `size`
         *     就是"取前 N 条"，要收紧就在界面上少列几条。
         */
        get: operations["list_videos_api_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/single-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collect Single Link */
        post: operations["collect_single_link_api_videos_single_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_api_videos__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Hide Video
         * @description 隐藏（情报流的"删除"）。不删媒体、不删稿子 —— 文件是全库唯一的原始产物。
         */
        patch: operations["hide_video_api_videos__video_id__hide_patch"];
        trace?: never;
    };
    "/api/videos/{video_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Video Media
         * @description 播放这条作品的本地媒体（支持 Range）。
         */
        get: operations["stream_video_media_api_videos__video_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Shots
         * @description 从这条作品已落地的成片里按时间点截一批帧，返回缩略图清单。
         */
        post: operations["create_shots_api_videos__video_id__shots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/shots/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shot Image
         * @description 把 `shots/` 里那张图交出去。三道判据见模块 docstring，越界一律 403。
         */
        get: operations["get_shot_image_api_videos__video_id__shots__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_videos__video_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Unhide Video */
        patch: operations["unhide_video_api_videos__video_id__unhide_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCreatorRequest */
        AddCreatorRequest: {
            /** Platform */
            platform?: string | null;
            /**
             * Tracking
             * @default true
             */
            tracking: boolean;
            /** Url */
            url: string;
        };
        /**
         * BenchmarkAnalysis
         * @description 一条口播稿的完整拆解结果（纯函数产物，V2 不落库）。
         */
        BenchmarkAnalysis: {
            /** Creator */
            creator: string;
            dos_and_donts: components["schemas"]["DosAndDonts"];
            /** Duration Seconds */
            duration_seconds: number;
            handoff: components["schemas"]["CreationHandoff"];
            hook: components["schemas"]["HookBreakdown"];
            /** Line By Line */
            line_by_line: components["schemas"]["LineBreakdown"][];
            /** Platform */
            platform: string;
            structure_progression: components["schemas"]["StructureProgression"];
            /** Title */
            title: string;
            /**
             * Total Chars
             * @description 所有有效行的字符总数（不含换行）。V1 误名为 totalWords。
             */
            total_chars: number;
            /** Version */
            version: string;
        };
        /** CancelResponse */
        CancelResponse: {
            /** Cancelled */
            cancelled: boolean;
            /** Task Id */
            task_id: string;
        };
        /**
         * CollectJobInfo
         * @description 一条已经排在 APScheduler 里的采集 job。
         */
        CollectJobInfo: {
            /** Id */
            id: string;
            /** Next Run Time */
            next_run_time?: string | null;
            /** Platform */
            platform: string;
        };
        /** ConfigUpdateResponse */
        ConfigUpdateResponse: {
            /** Changed Fields */
            changed_fields?: string[];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Platform */
            platform: string;
            /**
             * Requires Restart
             * @default false
             */
            requires_restart: boolean;
        };
        /**
         * CreationHandoff
         * @description 交给下游二创的交接包。
         */
        CreationHandoff: {
            /**
             * Core Contradiction
             * @description = hook.promise。
             */
            core_contradiction: string;
            /** Creator */
            creator: string;
            /**
             * Key Takeaways
             * @description 前 3 条被评成『可复用』的原句。
             */
            key_takeaways: string[];
            /** Platform */
            platform: string;
            /**
             * Recommended Mode
             * @description SHORT / LONG。
             */
            recommended_mode: string;
            /** Recommended Template */
            recommended_template: string;
            /** Source Title */
            source_title: string;
        };
        /**
         * Creator
         * @description DB 行（creators 表的 Pydantic 映射）。
         *
         *     V1 §7.24 看护：is_tracking 必须真布尔，DB 层有 CHECK (is_tracking IN (0, 1))。
         */
        Creator: {
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Follower Count */
            follower_count?: number | null;
            /** Id */
            id: number;
            /** Is Tracking */
            is_tracking: boolean;
            /** Metadata Json */
            metadata_json: string;
            /** Name */
            name: string;
            /** Platform */
            platform: string;
            /** Platform Id */
            platform_id: string;
            /** Profile Url */
            profile_url: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DosAndDonts */
        DosAndDonts: {
            /**
             * Avoid
             * @description 避坑清单（规范常量，每条视频相同）。
             */
            avoid: string[];
            /**
             * Borrow
             * @description 可借鉴清单（规范常量，每条视频相同）。
             */
            borrow: string[];
        };
        /** DraftCreate */
        DraftCreate: {
            /**
             * Content
             * @description 整篇正文，入库而不是落文件
             */
            content: string;
            /**
             * Source Video Id
             * @description 来源作品；删作品时这一列变 NULL，草稿不跟着删
             */
            source_video_id?: number | null;
            /**
             * Status
             * @description draft / published / archived
             * @default draft
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /**
             * Title
             * @description 草稿标题
             */
            title: string;
        };
        /**
         * DraftRecord
         * @description `drafts` 的 DB 行。
         */
        DraftRecord: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Source Video Id */
            source_video_id?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DraftScript
         * @description 一份二创脚本。字段是 V1 的形状（键名换成 snake_case）。
         */
        DraftScript: {
            /** Beats */
            beats: components["schemas"]["ScriptBeat"][];
            /**
             * Beats Template Key
             * @description **实际用了哪张分镜表**。`tool_demo` 没有自己的表，它的产出与 `tutorial_save_loop` 一字不差 —— 这个字段就是让那次降级看得见。
             */
            beats_template_key: string;
            /** Cards */
            cards: components["schemas"]["ScriptCard"][];
            /**
             * Estimated Duration Seconds
             * @description 总口播字数 / 4.0 取整，是换算不是测量。
             */
            estimated_duration_seconds: number;
            /** Film Job */
            film_job: string;
            /** Mode */
            mode: string;
            /**
             * Script Markdown
             * @description 完整的 script.md（V1 落盘的就是这一段）。
             */
            script_markdown: string;
            /**
             * Teleprompter Text
             * @description 纯提词器正文：`Sxx｜口播`，句间空行。
             */
            teleprompter_text: string;
            /** Template Key */
            template_key: string;
            /** Template Name */
            template_name: string;
            /** Title */
            title: string;
            /** Total Beats */
            total_beats: number;
            /** Version */
            version: string;
        };
        /**
         * DraftScriptRequest
         * @description `POST /api/generate-draft-script` 的 body。
         */
        DraftScriptRequest: {
            /**
             * Custom Instructions
             * @description V1 有这个字段但从未生效。今天非空即 422，不装。
             */
            custom_instructions?: string | null;
            /**
             * Mode
             * @description 回执字段，不改变分镜数量；要更短的本子请换 `short_fast`。
             * @default SHORT
             * @enum {string}
             */
            mode: "SHORT" | "LONG";
            /**
             * Template Key
             * @description 四张模板之一：tutorial_save_loop、judgment_first、tool_demo、short_fast。
             * @default tutorial_save_loop
             * @enum {string}
             */
            template_key: "tutorial_save_loop" | "judgment_first" | "tool_demo" | "short_fast";
            /**
             * Topic
             * @description 要写的主题。空则取 `video_id` 那条作品的标题。
             * @default
             */
            topic: string;
            /**
             * Video Id
             * @description 只为拿标题而存在；这个端点不读那条作品的口播稿（见模块 docstring）。
             */
            video_id?: number | null;
        };
        /**
         * DraftUpdate
         * @description 部分更新。**没带的字段不动**，所以四个键都默认 `None` = "我没说要改这个"。
         *
         *     `content=None` 与 `content=""` 是两回事：前者是"不改正文"，后者过不了这里的
         *     `min_length=1`（422），再往下也过不了 `DraftInput` 的空白判 —— 想清空正文
         *     今天没有入口，那是"删掉这篇稿子"而不是"把它写成空的"。
         */
        DraftUpdate: {
            /** Content */
            content?: string | null;
            /**
             * Source Video Id
             * @description 换一篇来源作品；不传＝不动这一列（解除关联要删了重建）
             */
            source_video_id?: number | null;
            /**
             * Status
             * @description draft / published / archived
             */
            status?: ("draft" | "published" | "archived") | null;
            /** Title */
            title?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Version */
            version: string;
        };
        /** HideRequest */
        HideRequest: {
            /** Reason */
            reason: string;
        };
        /**
         * HookBreakdown
         * @description 开篇黄金钩子的剖析。
         */
        HookBreakdown: {
            /** Description */
            description: string;
            /**
             * Promise
             * @description 核心承诺：首句超过 6 个字时就是首句本身（去掉句末标点）。
             */
            promise: string;
            /**
             * Punch Score
             * @description 92（首句 ≤35 字）或 85（更长），空稿兜底 60。规则常数，不是测量。
             */
            punch_score: number;
            /**
             * Sentence
             * @description 稿子的第一行（钩子本体）。
             */
            sentence: string;
            /**
             * Type
             * @description 命中的钩子模式名；5 条都不中时是『悬念吸引型』。
             */
            type: string;
            /**
             * Visible Evidence
             * @description 开场建议配的视觉素材（按标题关键词二选一）。
             */
            visible_evidence: string;
        };
        /**
         * LineBreakdown
         * @description 一行口播的职能拆解。
         */
        LineBreakdown: {
            /** Index */
            index: number;
            /** Reusable */
            reusable: string;
            /**
             * Role
             * @description 职能说明文案，V1 的 `role` 字段（它给的就是这句文案）。
             */
            role: string;
            /**
             * Role Key
             * @description 职能表里的键（hook/problem/…）；走进度兜底时没有键，为 null。
             */
            role_key?: string | null;
            /** Sentence */
            sentence: string;
            /**
             * Timestamp
             * @description 推算的 mm:ss 起点，按语速累计，不是稿子里的时间戳。
             */
            timestamp: string;
            /** Visual */
            visual: string;
        };
        /**
         * ManifestRecord
         * @description DB 行（manifests 表的 Pydantic 映射）。
         *
         *     清单**双写**：文件（`data/manifests/<...>.json`，审计与离线分析）
         *     + SQLite（前端历史列表查询）。V1 只有文件，于是"最近 20 次任务"
         *     要 glob 目录 + 逐个读 JSON + 排序 —— 慢，而且文件名格式一变就全废。
         *
         *     `content_json` 是完整清单的冗余副本：详情/审计仍然读文件（那才是权威源），
         *     这里存一份只是为了列表页不用回磁盘。
         */
        ManifestRecord: {
            /** Content Json */
            content_json: string;
            /** File Path */
            file_path: string;
            /** Id */
            id: number;
            /**
             * Schema Version
             * @default 2.0
             */
            schema_version: string;
            /** Task Id */
            task_id: string;
            /**
             * Written At
             * Format: date-time
             */
            written_at: string;
        };
        /** ManifestSummary */
        ManifestSummary: {
            /** File Path */
            file_path: string;
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Summary */
            summary: {
                [key: string]: number | string;
            };
            /** Task Id */
            task_id: string;
            /** Written At */
            written_at: unknown;
        };
        /** PagedResult[Video] */
        PagedResult_Video_: {
            /** Items */
            items: components["schemas"]["Video"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** PlatformControlStatus */
        PlatformControlStatus: {
            /** Enabled */
            enabled: boolean;
            /** Shadowed By Env */
            shadowed_by_env?: string[];
        };
        /**
         * PlatformControlUpdate
         * @description PUT 的请求体。只有一个字段，所以不搞 `exclude_unset` 那套"没写的保持原值" ——
         *     那套是为了一张表里多个字段准备的，这里只会让人以为可以省略。
         */
        PlatformControlUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** PlatformControlUpdateResponse */
        PlatformControlUpdateResponse: {
            /** Changed Fields */
            changed_fields?: string[];
            platform_control: components["schemas"]["PlatformControlStatus"];
            /**
             * Requires Restart
             * @default false
             */
            requires_restart: boolean;
        };
        /** PlatformSummary */
        PlatformSummary: {
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "own_off" | "master_off" | "absent";
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Health Checked At */
            health_checked_at?: string | null;
            /** Health Detail */
            health_detail?: string | null;
            /** Health Status */
            health_status?: string | null;
            /** Implemented */
            implemented: boolean;
            /** Name */
            name: string;
        };
        /** PlatformsResponse */
        PlatformsResponse: {
            /**
             * Master Enabled
             * @default true
             */
            master_enabled: boolean;
            /** Platforms */
            platforms: components["schemas"]["PlatformSummary"][];
        };
        /** RunDetail */
        RunDetail: {
            /** Manifest */
            manifest?: {
                [key: string]: unknown;
            } | null;
            run: components["schemas"]["TaskRunRecord"];
        };
        /** RunNowRequest */
        RunNowRequest: {
            /** Platform */
            platform: string;
        };
        /** RunNowResponse */
        RunNowResponse: {
            /** Platform */
            platform: string;
            /** Task Id */
            task_id: string;
            /** Task Name */
            task_name: string;
        };
        /**
         * ScheduleStatus
         * @description `GET /api/schedule`：配置 + 运行态两份**并排**。
         *
         *     两份分开是必须的：只看配置会说谎（改了没生效），只看 job 也会说谎
         *     （`scheduler.enabled: false` 时一条 job 都没有，而配置里明明写着 08:00）。
         */
        ScheduleStatus: {
            /** Collect Cron */
            collect_cron: string | null;
            /** Collect Limit */
            collect_limit: number | null;
            /** Collect Platforms */
            collect_platforms?: string[];
            /** Effective Platforms */
            effective_platforms?: string[];
            /** Jobs */
            jobs?: components["schemas"]["CollectJobInfo"][];
            /**
             * Master Enabled
             * @default true
             */
            master_enabled: boolean;
            /** Scheduler Enabled */
            scheduler_enabled: boolean;
            /**
             * Scheduler Running
             * @default false
             */
            scheduler_running: boolean;
            /** Shadowed By Env */
            shadowed_by_env?: string[];
            /** Skipped Platforms */
            skipped_platforms?: string[];
            /** Timezone */
            timezone: string;
        };
        /**
         * ScheduleUpdate
         * @description PUT 的请求体：**没出现的键保持原值**。
         *
         *     所以 `collect_cron: null` 是"关掉定时"，而整个键不写是"这次不改它"。这两件事必须分得开，
         *     否则前端只能"总是提交全表"，那等于每次保存都把别人的字段顺手写一遍。
         */
        ScheduleUpdate: {
            /** Collect Cron */
            collect_cron?: string | null;
            /** Collect Limit */
            collect_limit?: number | null;
            /** Collect Platforms */
            collect_platforms?: string[] | null;
        };
        /** ScheduleUpdateResponse */
        ScheduleUpdateResponse: {
            /** Changed Fields */
            changed_fields?: string[];
            /**
             * Requires Restart
             * @default false
             */
            requires_restart: boolean;
            schedule: components["schemas"]["ScheduleStatus"];
        };
        /** ScriptBeat */
        ScriptBeat: {
            /**
             * Channel
             * @description 三通道之一：真人出镜＋动效 / 真实录屏 / 全屏AI视频。
             */
            channel: string;
            /** Id */
            id: string;
            /**
             * Speech
             * @description 这一句的口播原文 —— 它一定来自分镜表，不来自模型。
             */
            speech: string;
            /**
             * Visual Cue
             * @description 内联画面指示，V1 的 `visualCue`（【画面：…】）。
             */
            visual_cue: string;
        };
        /** ScriptCard */
        ScriptCard: {
            /** Content */
            content: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** ShotFailureItem */
        ShotFailureItem: {
            /** At Seconds */
            at_seconds: number;
            /**
             * Reason
             * @description ffmpeg 的失败原文（截不出这一帧的真实原因，不并成一句'失败'）
             */
            reason: string;
        };
        /** ShotItem */
        ShotItem: {
            /**
             * At Seconds
             * @description 这一帧对应的时间点（已按文件名的量化精度对齐）
             */
            at_seconds: number;
            /**
             * Path
             * @description 相对 `data/` 的路径（与 `media_path` 同一套约定）
             */
            path: string;
            /**
             * Produced
             * @description True = 这次真的截了；False = 复用上一次的同一帧
             */
            produced: boolean;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Url
             * @description 出图地址，前端直接用；**不拼磁盘路径**
             */
            url: string;
        };
        /**
         * ShotRequest
         * @description 请求体。`at_seconds` 省略 = 按 `videos.duration_seconds` 均分。
         */
        ShotRequest: {
            /**
             * At Seconds
             * @description 要截的时间点（秒），来自分镜行；省略则按作品时长均分（最多 12 帧）
             */
            at_seconds?: number[] | null;
        };
        /** ShotsResponse */
        ShotsResponse: {
            /**
             * Cached
             * @description True = 这一帧都没有新截，全是复用上次的；界面上必须与'刚截好的'区分开
             */
            cached: boolean;
            /**
             * Failures
             * @description 某几秒截不出来时，原因在这里（不伪装成没发生）
             */
            failures: components["schemas"]["ShotFailureItem"][];
            /**
             * Ffmpeg Version Or Error
             * @description 产出这些帧的 ffmpeg 是哪一支；纯复用时为 null
             */
            ffmpeg_version_or_error: string | null;
            /**
             * Requested At
             * @description 实际去截的时间点（已去重、已限量）
             */
            requested_at: number[];
            /** Shots */
            shots: components["schemas"]["ShotItem"][];
            /** Video Id */
            video_id: number;
        };
        /**
         * SingleLinkParams
         * @description 收一条作品（`single_link`）：解析链接 → 判平台 → 走对应适配器。
         */
        SingleLinkParams: {
            /**
             * Url
             * @description 作品链接（分享短链也可以）
             */
            url: string;
        };
        /** StructureBeat */
        StructureBeat: {
            /** Core Job */
            core_job: string;
            /** Phase */
            phase: string;
            /**
             * Time Range
             * @description V1 的硬编码时间轴 —— 与这条视频的实际时长无关。
             */
            time_range: string;
        };
        /** StructureProgression */
        StructureProgression: {
            /** Beats */
            beats: components["schemas"]["StructureBeat"][];
            /** Density */
            density: string;
            /** Proof Moment */
            proof_moment: string;
            /** Reward Cadence */
            reward_cadence: string;
        };
        /** TaskAccepted */
        TaskAccepted: {
            /** Task Id */
            task_id: string;
        };
        /** TaskInfo */
        TaskInfo: {
            /** Cancellable */
            cancellable: boolean;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Params Schema */
            params_schema?: {
                [key: string]: unknown;
            };
            /** Platforms */
            platforms: string[];
            /** Timeout Seconds */
            timeout_seconds: number | null;
        };
        /**
         * TaskRunRecord
         * @description DB 行（task_runs 表的 Pydantic 映射）。
         *
         *     与 `TaskResult` 的区别：`TaskResult` 是**一次执行的产出**（handler 返回它），
         *     `TaskRunRecord` 是**这次执行的档案**（含 id / 时间戳 / 进度 / 清单路径）。
         *     前者活在一次调用里，后者要能被"任务历史"页面翻出来。
         *
         *     V1 §2 契约二看护：`status` 为终态时 `ended_at` 必填，DB 层有 CHECK 约束
         *     `status = 'running' OR ended_at IS NOT NULL`。
         */
        TaskRunRecord: {
            /**
             * Config Snapshot Json
             * @default {}
             */
            config_snapshot_json: string;
            /** Ended At */
            ended_at?: string | null;
            /** Error Text */
            error_text?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Manifest Path */
            manifest_path?: string | null;
            /**
             * Params Json
             * @default {}
             */
            params_json: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "success" | "partial" | "failed" | "timeout" | "cancelled";
            /** Summary Json */
            summary_json?: string | null;
            /** Task Name */
            task_name: string;
        };
        /**
         * Topic
         * @description `topics` 的 DB 行。
         */
        Topic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * TopicCreate
         * @description 新建选题的入参。`name` 的空判在 `TopicDraft` 里，不在这里重复一遍。
         */
        TopicCreate: {
            /** Description */
            description?: string | null;
            /**
             * Name
             * @description 选题名，全库唯一
             */
            name: string;
        };
        /**
         * TopicUpdate
         * @description 改选题。只有 `description` 可改，理由见 `TopicUpdatableFields`。
         *
         *     这里**不区分**"没传"与"传了 null"：只有一个可改字段，`update_fields()` 又一定被调用，
         *     所以清空描述就是 PATCH 一个 null。草稿那张表要区分（四列里挑一列改），
         *     两处的形状不同是字段数不同，不是各写各的。
         */
        TopicUpdate: {
            /** Description */
            description?: string | null;
        };
        /** TrackingRequest */
        TrackingRequest: {
            /** Tracking */
            tracking: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Video
         * @description DB 行（videos 表的 Pydantic 映射）。
         *
         *     V1 §7.25 看护：is_hidden + hidden_at + hidden_reason 内化墓碑。
         */
        Video: {
            /** Comment Count */
            comment_count?: number | null;
            /** Cover Path */
            cover_path?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Creator Id */
            creator_id?: number | null;
            /** Description */
            description?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Has Video
             * @default true
             */
            has_video: boolean;
            /** Hidden At */
            hidden_at?: string | null;
            /** Hidden Reason */
            hidden_reason?: string | null;
            /** Id */
            id: number;
            /**
             * Is Hidden
             * @default false
             */
            is_hidden: boolean;
            /** Like Count */
            like_count?: number | null;
            /**
             * Media Aux Paths Json
             * @default []
             */
            media_aux_paths_json: string;
            /** Media Path */
            media_path?: string | null;
            /** Media Source */
            media_source?: string | null;
            /**
             * Metadata Json
             * @default {}
             */
            metadata_json: string;
            /** Platform */
            platform: string;
            /** Platform Video Id */
            platform_video_id: string;
            /** Published At */
            published_at?: string | null;
            /** Share Count */
            share_count?: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** View Count */
            view_count?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    benchmark_analysis_api_benchmark_analysis_get: {
        parameters: {
            query: {
                /** @description `videos.id`（整数主键，不是平台作品 ID） */
                video_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_creators_api_creators_get: {
        parameters: {
            query?: {
                platform?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_creator_api_creators_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCreatorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_creator_api_creators__creator_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creator_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tracking_api_creators__creator_id__tracking_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creator_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_drafts_get: {
        parameters: {
            query?: {
                status?: ("draft" | "published" | "archived") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_api_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_api_drafts__draft_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_draft_api_drafts__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_events_api_events_get: {
        parameters: {
            query?: {
                /** @description 逗号分隔的 EventType */
                types?: string | null;
                since?: string | null;
                /** @description 只看这一次任务（带上才回放历史） */
                task_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_table_api_export_get: {
        parameters: {
            query?: {
                entity?: "videos" | "creators";
                format?: "csv" | "json";
                platform?: string | null;
                hidden?: "visible" | "hidden" | "all";
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_script_api_generate_draft_script_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftScriptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftScript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_manifests_api_manifests_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_api_manifests__manifest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                manifest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_control_api_platform_control_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformControlStatus"];
                };
            };
        };
    };
    update_platform_control_api_platform_control_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformControlUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformControlUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platforms_api_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformsResponse"];
                };
            };
        };
    };
    get_platform_config_api_platforms__platform__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_platform_config_api_platforms__platform__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_schema_api_platforms__platform__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_api_preflight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_schedule_api_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleStatus"];
                };
            };
        };
    };
    update_schedule_api_schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_now_api_schedule_run_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunNowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunNowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInfo"][];
                };
            };
        };
    };
    list_runs_api_tasks_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_tasks_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_tasks_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_tasks_runs__run_id__events_get: {
        parameters: {
            query?: {
                types?: string | null;
                since?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_task_api_tasks__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_schema_api_tasks__name__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_topics_get: {
        parameters: {
            query?: {
                /** @description 按名字模糊匹配 */
                search?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_api_topics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_api_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_api_topics__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_topic_api_topics__topic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_videos_api_videos_get: {
        parameters: {
            query?: {
                platform?: string | null;
                creator_id?: number | null;
                since?: string | null;
                search?: string | null;
                hidden?: "visible" | "hidden" | "all";
                sort?: "recent" | "benchmark";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult_Video_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collect_single_link_api_videos_single_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SingleLinkParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_video_api_videos__video_id__hide_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_video_media_api_videos__video_id__media_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shots_api_videos__video_id__shots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shot_image_api_videos__video_id__shots__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_videos__video_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unhide_video_api_videos__video_id__unhide_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
