"""transcripts: content_summary / key_points / summary_method (ADR-0015)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 08:33:54.339634+00:00

生成方式与 0001 一样是 autogenerate（先 `upgrade 0001` 到一个空库，再
`revision --autogenerate`），但**那个 CHECK 是补上去的**，这是 0001 那句
"照抄这条命令，别手写迁移"的一个已知例外：

    INTELLIGENCE_HUB_STORAGE__SQLITE_URL="sqlite+pysqlite:///<已 upgrade 0001 的空库>" \\
      python -X utf8 -m alembic -c alembic.ini revision --autogenerate \\
      -m "transcripts: content_summary / key_points / summary_method" --rev-id 0002

autogenerate 只报出三个列，`ck_transcripts_summary_method_enum` 它看不见 ——
SQLite 反射不出 CHECK 的原始文本（`alembic/env.py` 里 `compare_server_default=False`
的同一个盲区，见 `docs/specs/data-model.md §2` 末尾那条实施期修订）。
少了这条约束，`schema.py` 与迁移链就**永远差一条 CHECK**，而漂移看护对它是瞎的。
兜底是 `tests/unit/storage/test_schema_types.py::EXPECTED_CHECKS`（比全集不比子集），
这条迁移跑真库时它必须还是绿的。

`batch_alter_table` 是必需的，不是风格：SQLite 加 CHECK 只能"建新表 → 拷数据 → 改名"。
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic, CHECK 那条是手补（见模块 docstring）###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_method', sa.String(length=32), nullable=True))
        # 名字只写 `summary_method_enum`：batch 模式会按 metadata 的命名约定补前缀，
        # 写全 `ck_transcripts_...` 会得到 `ck_transcripts_ck_transcripts_summary_method_enum`
        # （第一版就踩了，量出来的 DDL 在 docs/progress/2026-09-24.md）。
        batch_op.create_check_constraint(
            'summary_method_enum',
            "summary_method IS NULL OR summary_method IN ('local-extractive','v1-imported')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        # **约束要先删，再删列**。batch 模式是"照当前表反射出一张新表 → 搬数据 → 改名"，
        # 反射回来的 CHECK 里还写着 `summary_method`；只 drop_column 的话新表带着一条
        # 引用不存在列的 CHECK，SQLite 在建表那一刻就 `no such column: summary_method` ——
        # 迁移会直接卡死在 0002 退不出去（本机第一跑就是这个报错）。
        # 名字同样只写裸的那一段：`drop_constraint` 与 `create_check_constraint` 走同一个
        # 命名约定，写全 `ck_transcripts_...` 这里会变成找不到约束。
        # `type_` 的合法值是 `'check'`（不是 `'constraint'`，那样直接 TypeError）。
        batch_op.drop_constraint('summary_method_enum', type_='check')
        batch_op.drop_column('summary_method')
        batch_op.drop_column('key_points')
        batch_op.drop_column('content_summary')
