"""add video_comments and video_metric_snapshots (ADR-0020)

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 15:19:16.660307+00:00

V2.1 T4.1 / T4.2（ADR-0020）：两张"作品的附属读数"表。

与 0002 不同，这一份**没有需要手补的约束** —— autogenerate 把
`ck_video_metric_snapshots_checkpoint_enum` 带出来了，因为它是随 `create_table`
一起下发的（0002 那次看不见 CHECK 是因为要给**已存在的表**加 CHECK，而 SQLite 反射不出
约束文本）。两条链的差别记在这里，是为了下一个加约束的人别照 0002 去"手补"一遍：
建表时写进 metadata 的约束，autogenerate 看得见。

`downgrade()` 是 `drop_table`，所以索引与约束跟着表一起没 —— 不需要像 0002 那样
"先删约束再删列"（那个坑只存在于 batch 改表的路上）。
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=191), nullable=False),
    sa.Column('parent_platform_comment_id', sa.String(length=191), nullable=True),
    sa.Column('author_platform_id', sa.String(length=191), nullable=True),
    sa.Column('author_name', sa.Text(), server_default='', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_comments_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_comments'))
    )
    with op.batch_alter_table('video_comments', schema=None) as batch_op:
        batch_op.create_index('idx_video_comments_published', ['video_id', 'published_at'], unique=False)
        batch_op.create_index('idx_video_comments_video', ['video_id'], unique=False)
        batch_op.create_index('uq_video_comments_video_platform_comment_id', ['video_id', 'platform', 'platform_comment_id'], unique=True)

    op.create_table('video_metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint', sa.String(length=16), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), server_default='{}', nullable=False),
    sa.CheckConstraint("checkpoint IN ('publish','24h','72h','7d','manual')", name=op.f('ck_video_metric_snapshots_checkpoint_enum')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_metric_snapshots_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_metric_snapshots'))
    )
    with op.batch_alter_table('video_metric_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_metric_snapshots_checkpoint', ['checkpoint'], unique=False)
        batch_op.create_index('uq_metric_snapshots_video_checkpoint', ['video_id', 'checkpoint'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index('uq_metric_snapshots_video_checkpoint')
        batch_op.drop_index('idx_metric_snapshots_checkpoint')

    op.drop_table('video_metric_snapshots')
    with op.batch_alter_table('video_comments', schema=None) as batch_op:
        batch_op.drop_index('uq_video_comments_video_platform_comment_id')
        batch_op.drop_index('idx_video_comments_video')
        batch_op.drop_index('idx_video_comments_published')

    op.drop_table('video_comments')
    # ### end Alembic commands ###
