"""add topics and drafts (ADR-0021)

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 15:40:04.016516+00:00

V2.2 T5.5（ADR-0021）：选题表与草稿表。`data-model.md` 从 V2.0 起就把这两节标成
「V2.2 实施」的预留契约，这一份就是把它兑现 —— 列与含义照 spec，没有增删。

**全程 autogenerate，没有手补**（与 0003 同一条链，不是照 0002 那条链）：
`ck_drafts_status_enum` 是被 `sa.CheckConstraint(...)` 带出来的，因为它随 `create_table`
一起下发，autogenerate 看得见。0002 那次要手补，是因为要给**已存在的表**加 CHECK，
而 SQLite 反射不出约束文本。两条链的差别记在这里，下一个加约束的人别照 0002 去补
已经存在的约束（`docs/progress/2026-09-24.md` T1.2b 有同一条说明）。

`downgrade()` 是两条 `drop_table`，索引与约束跟着表一起没 —— 不需要"先删约束再删列"
（那个坑只在 batch 改表这条路上）。两张表都没有需要回填的数据列，所以不需要
data migration（0002 那种加列才要）。

`uq_topics_name` 用的是**具名唯一索引**而不是 spec §2.8 那行内 `UNIQUE`：
表达的是同一个约束，但行内 UNIQUE 在 SQLite 的 `sqlite_master.sql` 里没有名字，
`downgrade()` drop 不掉 —— 正是本模块 `NAMING_CONVENTION` 当初立起来要防的那件事。
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index('uq_topics_name', ['name'], unique=True)

    op.create_table('drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_video_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','archived')", name=op.f('ck_drafts_status_enum')),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], name=op.f('fk_drafts_source_video_id_videos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts'))
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index('idx_drafts_status', ['status'], unique=False)
        batch_op.create_index('idx_drafts_updated', ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index('idx_drafts_updated')
        batch_op.drop_index('idx_drafts_status')

    op.drop_table('drafts')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('uq_topics_name')

    op.drop_table('topics')
    # ### end Alembic commands ###
